server:
  port: 8085
spring:
  application:
   name: guestbook
  jpa:
    hibernate:
      ddl-auto: create-drop

security:
  basic:
    enabled: false

management:
  security:
    enabled: false

---

spring:
  profiles: default
  jpa:
    database: HSQL

---

spring:
  profiles: cloud
  jpa:
    database: MYSQL